---
- name: debian | Installing Pre-Reqs
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present
  become: true

- name: debian | Adding HashiCorp GPG Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: true

- name: debian | Adding HashiCorp Repo
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release|lower }} main
    state: present
  become: true

- name: debian | Installing Nomad
  apt:
    name: nomad={{ nomad_version }}
    state: present
  become: true
