---
- name: service | Configuring Nomad Service
  template:
    src: etc/systemd/system/nomad.service.j2
    dest: /etc/systemd/system/nomad.service
  become: true

- name: service | Ensuring Nomad Service
  service:
    name: nomad
    state: started
    enabled: true
  become: true
